In [14]:
import numpy as np

In [15]:
demonstration_space = np.load('data/demonstration_space.npy', allow_pickle=True)
f_star = np.load('data/f_star.npy', allow_pickle=True)
rewards = np.load('data/rewards.npy', allow_pickle=True)
trajectory_space = np.load('data/trajectory_space.npy', allow_pickle=True)

In [18]:
for i in demonstration_space:
    print(i)
    print()

[[0.4        0.         0.25      ]
 [0.70869022 0.47326288 0.36093579]
 [0.75       0.         0.1       ]]

[[0.4        0.         0.25      ]
 [0.6759951  0.46239768 0.35613741]
 [0.75       0.         0.1       ]]

[[0.4        0.         0.25      ]
 [0.72188496 0.46279397 0.36147099]
 [0.75       0.         0.1       ]]

[[0.4        0.         0.25      ]
 [0.67752023 0.46236777 0.35559569]
 [0.75       0.         0.1       ]]

[[0.4        0.         0.25      ]
 [0.51483362 0.49960595 0.16021154]
 [0.75       0.         0.1       ]]

[[0.4        0.         0.25      ]
 [0.5333689  0.49542208 0.17309132]
 [0.75       0.         0.1       ]]

[[0.4        0.         0.25      ]
 [0.52167684 0.49520911 0.16549231]
 [0.75       0.         0.1       ]]

[[0.4        0.         0.25      ]
 [0.51337885 0.49535776 0.16935435]
 [0.75       0.         0.1       ]]

[[0.4        0.         0.25      ]
 [0.5113021  0.49959654 0.14190003]
 [0.75       0.         0.1       ]]

[[0.4     

In [3]:
from algos import generate_pairwise_comparisons, PBIRL

In [4]:
pairwise_comparisons = generate_pairwise_comparisons(trajs_feats=trajectory_space, trajs_reward=rewards)

In [ ]:
len(pairwise_comparisons)

In [6]:
pbirl = PBIRL(preferences=pairwise_comparisons, num_features=3, beta=1, mcmc_samples=5000, step_size=0.01)

In [ ]:
pbirl.run_mcmc()

In [ ]:
[ 0.90181928,  0.38649398, -0.19324699]

In [ ]:
np.array([1,2,3]).dot(np.array([1,2,3]))
np.dot(np.array([1,2,3]), np.array([1,2,3]))

In [11]:
from scipy.special import logsumexp

In [ ]:
logsumexp(-0.1)