In [1]:
import numpy as np
from env_1 import Env1
#from algos import *
import math
from scipy.stats import norm

#np.random.seed(42)

pybullet build time: Nov 28 2023 23:52:03


In [27]:
map_trajs = np.load('map_trajectories_11.2.npy')
optimal_traj = np.load('optimal_trajectory.11.2.npy')


In [28]:
len(mean_trajs)

2115

In [24]:
2115/15

141.0

In [25]:
mean_trajs.shape


(2115, 3, 3)

In [29]:
map_trajs[1:4,:,:]

array([[[0.4       , 0.        , 0.25      ],
        [0.65152496, 0.08690054, 0.43391381],
        [0.75      , 0.        , 0.1       ]],

       [[0.4       , 0.        , 0.25      ],
        [0.41417468, 0.48003244, 0.58374267],
        [0.75      , 0.        , 0.1       ]],

       [[0.4       , 0.        , 0.25      ],
        [0.65152496, 0.08690054, 0.43391381],
        [0.75      , 0.        , 0.1       ]]])

In [30]:
mean_trajs[1:4]

array([[[0.4       , 0.        , 0.25      ],
        [0.65152496, 0.08690054, 0.43391381],
        [0.75      , 0.        , 0.1       ]],

       [[0.4       , 0.        , 0.25      ],
        [0.41417468, 0.48003244, 0.58374267],
        [0.75      , 0.        , 0.1       ]],

       [[0.4       , 0.        , 0.25      ],
        [0.65152496, 0.08690054, 0.43391381],
        [0.75      , 0.        , 0.1       ]]])

In [8]:
traj_avg = 0
for i in range(0,mean_trajs.shape[0], 15):
    traj_avg += mean_trajs[i:i+15]
final_trajs = traj_avg/15

In [10]:
final_trajs[0]

array([[3.76      , 0.        , 2.35      ],
       [5.59829526, 2.29362567, 4.36625531],
       [7.05      , 0.        , 0.94      ]])

In [10]:
optimal_traj

array([[ 0.3       , -0.3       ,  0.15      ],
       [ 0.62142828,  0.44430013,  0.53310586],
       [ 0.6       ,  0.5       ,  0.3       ]])

In [5]:
traj_1 = final_trajs[0]

traj_9 = final_trajs[9]

# initialize environment
env = Env1(visualize=True)
print(env.feature_count(traj_1, [255, 0, 0]))
print(env.feature_count(traj_9, [0, 255, 0]))
print(env.feature_count(optimal_traj, [0, 0, 0]))

startThreads creating 1 threads.
starting thread 0
started thread 0 
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
X11 functions dynamically loaded using dlopen/dlsym OK!
X11 functions dynamically loaded using dlopen/dlsym OK!
Creating context
Created GL 3.3 context
Direct GLX rendering context obtained
Making context current
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=NVIDIA GeForce RTX 4090/PCIe/SSE2
GL_VERSION=3.3.0 NVIDIA 560.35.03
GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
pthread_getconcurrency()=0
Version = 3.3.0 NVIDIA 560.35.03
Vendor = NVIDIA Corporation
Renderer = NVIDIA GeForce RTX 4090/PCIe/SSE2
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0 
MotionThreadFunc thread started
ven = NVIDIA Corporation
ven = NVIDIA Corporation
[ 0.40366696 -0.72697705  0.16294701]
[ 0.68794754 -0.8227066   0.47327181]
[ 3.23399574 -0.86196891 10.45872845]


In [6]:

env.reward([3.23399574, -0.86196891, 10.45872845], [1, 0.1, -0.01])

3.0432115645

In [7]:
env.reward([ 0.68794754, -0.8227066,   0.47327181], [1, 0.1, -0.01])

0.6009441619000001

In [8]:
env.reward([ 0.68794754, -0.8227066,   0.47327181], [1, 0.1, -0.01])

0.6009441619000001