## MEAN Policy: reward is the mean of the mcmc samples

In [1]:
import numpy as np
from env_1 import Env1
#from algos import *
import math
from scipy.stats import norm

#np.random.seed(42)

pybullet build time: Nov 28 2023 23:52:03


In [2]:
mean_trajs = np.load('mean_trajectories.npy')
optimal_traj = np.load('optimal_trajectory.npy')

In [3]:
env = Env1(visualize=True)
print(env.feature_count(mean_trajs[3], [0, 255, 0], T=2.0))

startThreads creating 1 threads.
starting thread 0
started thread 0 
argc=2
argv[0] = --unused
argv[1] = --start_demo_name=Physics Server
ExampleBrowserThreadFunc started
X11 functions dynamically loaded using dlopen/dlsym OK!
X11 functions dynamically loaded using dlopen/dlsym OK!
Creating context
Created GL 3.3 context
Direct GLX rendering context obtained
Making context current
GL_VENDOR=NVIDIA Corporation
GL_RENDERER=NVIDIA GeForce RTX 4090/PCIe/SSE2
GL_VERSION=3.3.0 NVIDIA 560.35.03
GL_SHADING_LANGUAGE_VERSION=3.30 NVIDIA via Cg compiler
pthread_getconcurrency()=0
Version = 3.3.0 NVIDIA 560.35.03
Vendor = NVIDIA Corporation
Renderer = NVIDIA GeForce RTX 4090/PCIe/SSE2
b3Printf: Selected demo: Physics Server
startThreads creating 1 threads.
starting thread 0
started thread 0 
MotionThreadFunc thread started
ven = NVIDIA Corporation
ven = NVIDIA Corporation
[ 0.52925421 -0.95781944  0.28011002]


In [4]:
env.reward([ 0.52925421, -0.95781944,  0.28011002], [1, 0.1, -0.01])

0.4306711657999999

In [7]:
print(env.feature_count(optimal_traj, [0, 255, 0], T=2.0))

[ 3.23399574 -0.86196891 10.45872845]


In [8]:
env.reward([ 3.23399574, -0.86196891, 10.45872845], [1, 0.1, -0.01])

3.0432115645

In [9]:
(3.0432115645 - 0.4306711657999999)/2

1.30627019935

In [10]:
print(env.feature_count(mean_trajs[13], [0, 255, 0], T=2.0))

[ 3.23399574 -0.86196891 10.45872845]


In [11]:
env.reward([3.23399574, -0.86196891, 10.45872845], [1, 0.1, -0.01])

3.0432115645

In [12]:
(mean_trajs[13] + mean_trajs[3])/2

array([[ 0.3       , -0.3       ,  0.15      ],
       [ 0.62566216,  0.46812475,  0.5409154 ],
       [ 0.6       ,  0.5       ,  0.3       ]])

In [24]:
print(env.feature_count((mean_trajs[23]+mean_trajs[13] + mean_trajs[3])/3, [0, 255, 0], T=2.0))

[ 0.50921415 -0.89276971  0.25929906]


In [25]:
env.reward([ 0.50921415, -0.89276971,  0.25929906], [1, 0.1, -0.01])

0.41734418840000004

In [28]:
(3.0432115645 - 0.41734418840000004)/3

0.8752891253666667

In [29]:
print(env.feature_count(mean_trajs[3], [0, 255, 0], T=2.0))
print(env.feature_count(mean_trajs[13], [0, 255, 0], T=2.0))
print(env.feature_count(mean_trajs[23], [0, 255, 0], T=2.0))

[ 0.52925421 -0.95781944  0.28011002]
[ 3.23399574 -0.86196891 10.45872845]
[ 3.23399574 -0.86196891 10.45872845]


In [37]:
print(env.feature_count(mean_trajs[33], [0, 255, 0], T=2.0))

[ 3.23399574 -0.86196891 10.45872845]


In [30]:
print(env.reward([ 0.52925421, -0.95781944,  0.28011002], [1, 0.1, -0.01]))
print(env.reward([ 3.23399574, -0.86196891, 10.45872845], [1, 0.1, -0.01]))
print(env.reward([ 3.23399574, -0.86196891, 10.45872845], [1, 0.1, -0.01]))
print(env.reward([ 3.23399574, -0.86196891, 10.45872845], [1, 0.1, -0.01]))

0.4306711657999999
3.0432115645
3.0432115645


In [38]:
(3.0432115645 - 0.4306711657999999)/8

0.3265675498375

: 

In [34]:
1.30627019935/3

0.4354233997833334

In [ ]:
traj_avg = 0
for i in range(0,mean_trajs.shape[0], 10):
    traj_avg += mean_trajs[i:i+10]

In [ ]:
traj_avg = traj_avg/261

In [ ]:
traj_avg

In [ ]:
traj_1 = traj_avg[0]

traj_9 = traj_avg[9]

# initialize environment
env = Env1(visualize=True)
print(env.feature_count(traj_1, [255, 0, 0], T=2.0))
print(env.feature_count(traj_9, [0, 255, 0], T=2.0))
print(env.feature_count(optimal_traj, [0, 0, 0], T=2.0))

In [ ]:
[0.68794754 -0.8227066   0.47327181]
[3.23399574 -0.86196891 10.45872845]

In [ ]:
env.reward([0.40366696, -0.72697705,  0.16294701], [1, 0.1, -0.01])

In [ ]:
env.reward([3.23399574, -0.86196891, 10.45872845], [1, 0.1, -0.01])

In [ ]:
(3.0432115645 - 0.32933978490000004)/2

## MAP Policy

In [ ]:
import numpy as np
from env_1 import Env1
#from algos import *
import math
from scipy.stats import norm

map_trajs = np.load('map_trajectories_11.1.npy')
optimal_traj = np.load('optimal_trajectory.11.1.npy')

In [ ]:
print(len(map_trajs))

In [ ]:
traj_avg = 0
for i in range(0,map_trajs.shape[0], 10):
    traj_avg += map_trajs[i:i+10]
final_trajs = traj_avg/261

In [ ]:
traj_1 = final_trajs[0]

traj_9 = final_trajs[9]

# initialize environment
env = Env1(visualize=True)
print(env.feature_count(traj_1, [255, 0, 0], T=2.0))
print(env.feature_count(traj_9, [0, 255, 0], T=2.0))
print(env.feature_count(optimal_traj, [0, 0, 0], T=2.0))